### ISSUE TITLE
The .font-size mixin is broken.

### ISSUE THREAD

**Issue by randallbruder** [alliswell/Less#16]
The `.font-size` mixin (`style.less`, line 552) looks like this:

``` css
.font-size(@size){
    @rem-value: (@size / 10);
    @px-value: @size;
    @lineHeight: (@size * 1.48);
    line-height: @lineHeight+0px;
    font-size: ~"@{px-value}px"; 
    font-size: ~"@{rem-value}rem";
}
```

which, when compiled, causes the last two lines to look like this:

``` css
font-size: 10pxpx; 
font-size: 10pxrem;
```

because the `@size` being passed in contains a 'px'. It should be written this way:

``` css
.font-size(@size){
    @rem-value: (@size / 10);
    @px-value: @size;
    @lineHeight: (@size * 1.48);
    line-height: @lineHeight;
    font-size: unit(@px-value,px);
    font-size: unit(@rem-value,rem);
}
```
